
ALTER TABLE GC_BOARD_REPLY drop CONSTRAINT BOARD_REPLY_FK;
ALTER TABLE GC_QNA_REPLY drop CONSTRAINT QNA_REPLY_FK;


DROP TABLE GC_BOARD_REPLY;
DROP TABLE GC_BOARD; 
DROP SEQUENCE GC_BOARD_SEQ;
DROP TABLE GC_QNA_REPLY;
DROP TABLE GC_QNA; 
DROP SEQUENCE GC_QNA_SEQ;

COMMIT;

/* GC_BOARD 테이블 (자유게시판) */
CREATE TABLE GC_BOARD (
  BOARD_ID NUMBER(10)          NOT NULL PRIMARY KEY,  --BOARD 고유키
  USERID   VARCHAR2(12 CHAR)   NOT NULL,              --사용자 아이디
  TITLE    VARCHAR2(30 CHAR)   NOT NULL,              --제목
  CONTENTS VARCHAR2(3000 CHAR) NOT NULL,              --내용
  WDATE    DATE                NOT NULL,              --작성일
  COUNT    NUMBER(10)          NOT NULL               --조회수  
);
CREATE SEQUENCE GC_BOARD_SEQ;

/* GC_BOARD_REPLY 테이블 (자유게시판 댓글) */
CREATE TABLE GC_BOARD_REPLY (
  BOARD_ID NUMBER(10)         NOT NULL,  --GC_BOARD 테이블로 외래키 적용
  USERID   VARCHAR2(12 CHAR)  NOT NULL,  --사용자 아이디
  CONTENTS VARCHAR2(100 CHAR) NOT NULL,  --내용
  WDATE    DATE               NOT NULL   --작성일
);
ALTER TABLE GC_BOARD_REPLY ADD CONSTRAINT BOARD_REPLY_FK FOREIGN KEY (BOARD_ID)
REFERENCES GC_BOARD(BOARD_ID) ON DELETE CASCADE;


/* GC_QNA 테이블 (고객센터) */
CREATE TABLE GC_QNA (
  QNA_ID   NUMBER(10)          NOT NULL PRIMARY KEY,  --QNA 고유키
  USERID   VARCHAR2(12 CHAR)   NOT NULL,              --사용자 아이디
  TITLE    VARCHAR2(30 CHAR)   NOT NULL,              --제목
  CONTENTS VARCHAR2(3000 CHAR) NOT NULL,              --내용
  WDATE    DATE                NOT NULL,              --작성일
  COUNT    NUMBER(10)          NOT NULL               --조회수  
);
CREATE SEQUENCE GC_QNA_SEQ;

/* GC_QNA_REPLY 테이블 (고객센터 댓글) */
CREATE TABLE GC_QNA_REPLY (
  QNA_ID   NUMBER(10)         NOT NULL,  --GC_BOARD 테이블로 외래키 적용
  USERID   VARCHAR2(12 CHAR)  NOT NULL,  --사용자 아이디
  CONTENTS VARCHAR2(100 CHAR) NOT NULL,  --내용
  WDATE    DATE               NOT NULL   --작성일
  
);

ALTER TABLE GC_QNA_REPLY ADD CONSTRAINT QNA_REPLY_FK FOREIGN KEY (QNA_ID)
REFERENCES GC_QNA(QNA_ID) ON DELETE CASCADE;


COMMIT;