
DROP TABLE GC_THEATER_SCHEDULE; 
DROP SEQUENCE GC_THEATER_SCHEDULE_SEQ;

/* GC_THEATER_SCHEDULE 테이블 (영화관) */
CREATE TABLE GC_THEATER_SCHEDULE (
  THEATER_SCHEDULE_ID NUMBER(10) NOT NULL PRIMARY KEY,
  THEATER_ID          NUMBER(10) NOT NULL,             --THEATER 고유키
  MOVIE_ID            NUMBER(10) NOT NULL,             --MOVIE 고유키
  MSTARTHOUR          DATE       NOT NULL,
  MENDHOUR            DATE       NOT NULL
);
CREATE SEQUENCE GC_THEATER_SCHEDULE_SEQ;


/* GC_THEATER_SCHEDULE 데이터 삽입 */

--서울 신촌 지점 1관 시간표
INSERT INTO GC_THEATER_SCHEDULE VALUES (GC_THEATER_SCHEDULE_SEQ.NEXTVAL, 1, 1, TO_DATE('09:00', 'HH24:MI'), TO_DATE('11:04', 'HH24:MI'));
INSERT INTO GC_THEATER_SCHEDULE VALUES (GC_THEATER_SCHEDULE_SEQ.NEXTVAL, 1, 1, TO_DATE('12:00', 'HH24:MI'), TO_DATE('14:04', 'HH24:MI'));
INSERT INTO GC_THEATER_SCHEDULE VALUES (GC_THEATER_SCHEDULE_SEQ.NEXTVAL, 1, 1, TO_DATE('18:00', 'HH24:MI'), TO_DATE('20:04', 'HH24:MI'));

COMMIT;
