
ALTER TABLE GC_THEATER_SEAT drop CONSTRAINT THEATER_SEAT_FK;

DROP TABLE GC_THEATER_SEAT;

/* GC_THEATER_SEAT 테이블 (영화관 좌석) */
CREATE TABLE GC_THEATER_SEAT (
  THEATER_ID NUMBER(10)       NOT NULL,                                                    --GC_THEATER 테이블로 외래키 적용  
  SEAT       VARCHAR2(3 CHAR) NOT NULL,                                                    --좌석 위치 (A01, B02, C03)
  ISRESERVED VARCHAR2(5 CHAR) NOT NULL CHECK(ISRESERVED = 'TRUE' OR ISRESERVED = 'FALSE')  --예약 여부
);


ALTER TABLE GC_THEATER_SEAT ADD CONSTRAINT THEATER_SEAT_FK FOREIGN KEY (THEATER_ID) REFERENCES GC_THEATER(THEATER_ID) ON DELETE CASCADE;


COMMIT;